/**
 * Deterministic doc ID for `supplierSkuMap/{mapId}`, keyed by supplier +
 * supplierSku per docs/SCHEMA.md §7. A deterministic ID (rather than an
 * autogenerated one) both guarantees uniqueness — the same supplier code
 * can only ever map to one skuCode — and lets a lookup be a direct doc
 * get() instead of a query.
 */
export function supplierSkuMapId(supplier: string, supplierSku: string): string {
  const slug = (value: string) =>
    value
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')

  const supplierSlug = slug(supplier)
  const supplierSkuSlug = slug(supplierSku)
  if (!supplierSlug || !supplierSkuSlug) {
    throw new Error('supplier and supplierSku must both contain at least one alphanumeric character.')
  }
  return `${supplierSlug}__${supplierSkuSlug}`
}
