import { onCall, HttpsError } from 'firebase-functions/v2/https'
import { getFirestore, FieldValue } from 'firebase-admin/firestore'
import { validateDonorIntake } from './lib/validateDonorIntake.js'

export const intakeDonor = onCall(async (request) => {
  if (request.auth?.token?.staff !== true) {
    throw new HttpsError('permission-denied', 'Staff only.')
  }

  const data = request.data ?? {}
  try {
    validateDonorIntake(data)
  } catch (err) {
    throw new HttpsError('invalid-argument', err.message)
  }

  const db = getFirestore()

  // Warn on a likely duplicate, never block — a re-purchase and a
  // data-entry mistake look the same here, and the person doing intake
  // is better placed to judge which than a hard rule is.
  let warning = null
  if (data.imei) {
    const existing = await db
      .collection('donors')
      .where('imei', '==', data.imei)
      .where('status', '==', 'intact')
      .limit(1)
      .get()
    if (!existing.empty) {
      warning = `An intact donor with this IMEI already exists (${existing.docs[0].id}).`
    }
  }

  const donorRef = db.collection('donors').doc()
  const movementRef = db.collection('stockMovements').doc()

  await db.runTransaction(async (tx) => {
    tx.set(donorRef, {
      model: data.model,
      imei: data.imei || '',
      imeiBlankReason: data.imei ? '' : data.imeiBlankReason,
      purchaseCost: data.purchaseCost,
      purchaseCurrency: data.purchaseCurrency,
      fxRateUsed: data.purchaseCurrency === 'CAD' ? null : data.fxRateUsed,
      purchaseDate: FieldValue.serverTimestamp(),
      source: data.source,
      supplierRef: data.supplierRef || '',
      condition: data.condition,
      status: 'intact',
      teardownId: '',
      resoldPrice: null,
      resoldDate: null,
      resoldBuyerId: '',
      notes: data.notes || '',
    })

    // Doc ID is autogenerated, not derived from the donor — the ledger is
    // append-only and a correction is a new row against the same donor,
    // so a donorId-derived ID would collide on the first correction.
    // ref/itemId do the linking back to the donor instead.
    tx.set(movementRef, {
      movementId: movementRef.id,
      at: FieldValue.serverTimestamp(),
      type: 'receive',
      skuCode: null,
      itemId: donorRef.id,
      qty: 1,
      unitCost: data.purchaseCost,
      ref: donorRef.id,
      brand: 'mobisource',
      note: '',
    })
  })

  return { donorId: donorRef.id, warning }
})
