import { onCall, HttpsError } from 'firebase-functions/v2/https'
import { getFirestore, FieldValue } from 'firebase-admin/firestore'
import type { WithFieldValue } from 'firebase-admin/firestore'
import { validateDonorIntake } from './lib/validateDonorIntake.js'
import type { DonorIntakeInput } from './lib/validateDonorIntake.js'
import type { Donor, StockMovement } from './lib/types.js'

export const intakeDonor = onCall<DonorIntakeInput>(async (request) => {
  const token = request.auth?.token as Record<string, unknown> | undefined
  if (token?.staff !== true) {
    throw new HttpsError('permission-denied', 'Staff only.')
  }

  const data = request.data ?? {}
  try {
    validateDonorIntake(data)
  } catch (err) {
    throw new HttpsError('invalid-argument', (err as Error).message)
  }

  const db = getFirestore()

  // Warn on a likely duplicate, never block — a re-purchase and a
  // data-entry mistake look the same here, and the person doing intake
  // is better placed to judge which than a hard rule is.
  let warning: string | null = null
  if (data.imei) {
    const existing = await db
      .collection('donors')
      .where('imei', '==', data.imei)
      .where('status', '==', 'intact')
      .limit(1)
      .get()
    if (!existing.empty) {
      warning = `An intact donor with this IMEI already exists (${existing.docs[0].id}).`
    }
  }

  const donorRef = db.collection('donors').doc()
  const movementRef = db.collection('stockMovements').doc()

  await db.runTransaction(async (tx) => {
    const donor: WithFieldValue<Donor> = {
      model: data.model as string,
      imei: (data.imei as string) || '',
      imeiBlankReason: data.imei ? '' : (data.imeiBlankReason as string),
      purchaseCost: data.purchaseCost as Donor['purchaseCost'],
      purchaseCurrency: data.purchaseCurrency as Donor['purchaseCurrency'],
      fxRateUsed: data.purchaseCurrency === 'CAD' ? null : (data.fxRateUsed as number),
      purchaseDate: FieldValue.serverTimestamp(),
      source: data.source as Donor['source'],
      supplierRef: (data.supplierRef as string) || '',
      condition: data.condition as Donor['condition'],
      status: 'intact',
      teardownId: '',
      resoldPrice: null,
      resoldDate: null,
      resoldBuyerId: '',
      notes: (data.notes as string) || '',
    }
    tx.set(donorRef, donor)

    // Doc ID is autogenerated, not derived from the donor — the ledger is
    // append-only and a correction is a new row against the same donor,
    // so a donorId-derived ID would collide on the first correction.
    // ref/itemId do the linking back to the donor instead.
    const movement: WithFieldValue<StockMovement> = {
      movementId: movementRef.id,
      at: FieldValue.serverTimestamp(),
      type: 'receive',
      skuCode: null,
      itemId: donorRef.id,
      qty: 1,
      unitCost: data.purchaseCost as StockMovement['unitCost'],
      ref: donorRef.id,
      brand: 'mobisource',
      note: '',
    }
    tx.set(movementRef, movement)
  })

  return { donorId: donorRef.id, warning }
})
